### PR TITLE
#10 Add a configuration option for the naming convention and use it d…

### PR DESCRIPTION
**Pull request by yanislavm**
I added in the settings an option the user to select the naming convention ( Camel Case or Snake Case ) that will be used for the method name generation.

### CODE REVIEW

**Review by Hazem-Ben-Khalfallah — APPROVED** [review]

**Comment by Hazem-Ben-Khalfallah** [comment]
@yanislavm I detected a problem when changing the naming convention in the IDE settings. It is not taking automatically into account.

**Comment by yanislavm** [comment]
Hi @Hazem-Ben-Khalfallah 
Can you please give me more details?

**Comment by Hazem-Ben-Khalfallah** [comment]
here is how to reproduce the issue:
Selection_005
when I change the naming convention in setting (**1**), the apply button (**2**) remains disabled as if it did not detect any change.
Even if you close the setting popup and create a new test case, it continues to use the old naming convention value.

**Comment by yanislavm** [comment]
Hi @Hazem-Ben-Khalfallah 
please have a look at https://github.com/Hazem-Ben-Khalfallah/test-cherry/pull/12

Thanks and Kind Regards,
Yani

**Pull request merged**
