### PR TITLE
Closes #7 - Adding support for IntelliJ 2021

### LINKED ISSUE #7: Support for IntelliJ Idea 2021
Hello dear author
Can you please add support for IntelliJ Idea 2021+

Thanks and Kind Regards

### PR DESCRIPTION
**Pull request by yanislavm**

### CODE REVIEW

**Comment by yanislavm** [comment]
@Hazem-Ben-Khalfallah 
Do you have an idea why locally the build was passing but on the pipeline it is not?

**Comment by Hazem-Ben-Khalfallah** [comment]
@yanislavm the pipeline is not configured correctly in github. Never got the time to make it work properly.

**Comment by yanislavm** [comment]
Thanks for the reply @Hazem-Ben-Khalfallah 
But then how are you releasing the changes? Are you doing it manually and if so what will do with the PR?

**Comment by Hazem-Ben-Khalfallah** [comment]
@yanislavm I just fixed the pipeline. You can rebase your branch on **master** and re-push now. IT should work.

**Comment by yanislavm** [comment]
@Hazem-Ben-Khalfallah it is now rebased

**Review by Hazem-Ben-Khalfallah — APPROVED** [review]

**Comment by Hazem-Ben-Khalfallah** [comment]
thank you @yanislavm!
The new plugin version will be submitted to Intellij Plugin Repository today. Plugin validation can take sometimes 24h before making it available in the marketplace.

**Pull request merged**
